### ISSUE TITLE
[🐞]: Flags Crash the Game When Used With a Banner Pattern in a Loom While Epic Knights is Installed

### ISSUE THREAD

**Issue by Anonagonn** [MehVahdJukaar/Supplementaries#1068]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.8.14

### Moonlight Lib Version

moonlight-1.20-2.11.33-forge

### Issue Detail

Epic Knights version: [1.20.1-forge]-Epic-Knights-9.8
Crash log: https://pastebin.com/5xBmaK2h
latest.log (too big for pastebin): https://zerobin.org/?7810a32feaba33fc#EJW4BYVJwW5FP81N23a4mSuyngnfwymgYrtLNXgyyw9N

Steps to recreate the problem:
•Place a flag into the loom with any banner pattern (both modded and vanilla patterns caused a crash)
•Place any dye into the loom to complete the recipe
•The game will crash trying to load a preview of the flag

Copying a banner pattern onto a flag by combining it with an existing banner that utilizes that pattern does not cause a crash, though unsupported patterns from mods do result in missing textures

**Comment by MehVahdJukaar** [comment]
try on a new world. remove supplementaries, place some random shields from epic knghts mod in same setup

**Comment by Anonagonn** [comment]
> try on a new world. remove supplementaries, place some random shields from epic knghts mod in same setup

I tested this as best I could but I wasn't able to achieve the same conditions as the Supplementaries flags, as the shields from Epic Knights can't be placed in the loom, you can only copy existing banners onto them using the crafting table. Banner patterns from vanilla Minecraft work fine, banner patterns from mods are filtered out and the resulting shield only sports the base color of the banner. I tested this with a range of shields, and specifically tried the "pavise" shield cited in the initial crash report. I finally managed to achieve a crash by applying a banner with a modded pattern to it, placing it down as a block, picking it up, and attempting to place it again. Though in my uneducated opinion it doesn't seem to be related to the initial issue based on the logs
Crash log: https://gist.github.com/Anonagonn/54a244ecfede82566597166b0c0aeccb
latest.log: https://gist.github.com/Anonagonn/c331e73e9df7262598c3783f3af2904b

**Comment by MehVahdJukaar** [comment]
yeah that seems from waila. For that other one i have no clue. From what i can see i see no other way for it to happen other than the BannerBlock.byColor() call returnin a shield from that mod instead of a banner block, somehow. Middle click all vanilla banneres(need at least 1 pattern)

**Comment by MehVahdJukaar** [comment]
did you try middle clicking vanilla banners?

**Comment by meeprdib** [comment]
Seems fixed on their end.
